### PR TITLE
Add Formater to serialize Deep hash to KeyValue

### PR DESCRIPTION
**Pull request by ombr**
Some logging service only parse key_value, with this formater we can log deep hash and make queries on it.

### CODE REVIEW

**Comment by ombr** [comment]
https://github.com/roidrage/lograge/pull/282

**Comment by ombr** [comment]
https://spoonconsulting.atlassian.net/browse/SP-1460

**Comment by iloveitaly** [comment]
@ombr could you rebase on master and add a changelog entry?

**Comment by ombr** [comment]
@iloveitaly Sorry for the delay. It is done ;-)

**Comment by iloveitaly** [comment]
@ombr it looks like CI is failing, could you take a look?

**Comment by ombr** [comment]
@iloveitaly  I think it should be good now. I fixed rubocop and the specs but I had specs failling on my branch.

```
 6) Lograge::Formatters::Logstash includes the 'action' key/value
     Failure/Error: require 'logstash-event'
     
     LoadError:
       cannot load such file -- logstash-event
     # ./lib/lograge/formatters/logstash.rb:17:in `load_dependencies'
     # ./lib/lograge/formatters/logstash.rb:9:in `call'
     # ./spec/formatters/logstash_spec.rb:15:in `block (2 levels) in <top (required)>'
     # ./spec/formatters/logstash_spec.rb:38:in `block (2 levels) in <top (required)>'
```

But I think it is not related.

**Comment by ombr** [comment]
@iloveitaly Can you take a look on this one ? Thanks in advance.

**Comment by iloveitaly** [comment]
@ombr Looks great! Thanks.

Would be great to add a usage example to the readme.

**Pull request merged**
