### PR TITLE
Added option to enable/disable rack logger

### PR DESCRIPTION
**Pull request by techthumb**

### CODE REVIEW

**Comment by pxlpnk** [comment]
@techthumb Would you be willing to rebase this with master? 
Quite something changed since you proposed this change.

**Comment by techthumb** [comment]
It appears that similar functionality is already merged in 25e391c307e738d71beae08b97c55b83ad773ff8. 
It probably makes sense to close this issue.

**Comment by pxlpnk** [comment]
Yeah I wasn't sure. the Semantics are a bit different but the code seems to achieve the same result.

Should we close this issue then?

**Comment by benlovell** [comment]
@techthumb thanks for you efforts. Closing for 25e391c.

**Pull request closed without merging**
