### PR TITLE
Prepare for 0.3.2 release

### PR DESCRIPTION
**Pull request by benlovell**

### CODE REVIEW

**Comment by benlovell** [comment]
Gah rubocop what is this I don't even :scream:

**Comment by pxlpnk** [comment]
Seems like that cop was added recently: https://github.com/bbatsov/rubocop/blob/9276d072f4f2eb09d7ac87cd7b1afc3c9531b74c/config/enabled.yml#L131-L133

If we don't agree with it we could still disable it.

**Comment by benlovell** [comment]
@pxlpnk I've resolved these in #121

**Comment by pxlpnk** [comment]
:+1: 

this brings up the issue on how we want to deal with changing style guides.

**Pull request merged**
