### PR TITLE
Add support for Action Cable

### PR DESCRIPTION
**Pull request by xlts**
Refactor log subscribers & create a new one to support logging of Action Cable events

Monkey-patch Action Cable server class to silence default Action Cable logger

Monkey-patch Action Cable Channel and Connection classes to support logging subscribe, unsubscribe, connect & disconnect events

Update log formatters to support Action Cable log data

### CODE REVIEW

**Comment by xlts** [comment]
Two important remarks here:

1. I decided to silence the default Action Cable logger (defined in `ActionCable::Server::Base`) completely - the framework code is littered with multiple `logger` calls in plenty of classes. Monkey-patching it would be utterly painful and could leave the code extremely hard to maintain in case of a change in Action Cable itself. As a consequence, calling `logger` e.g. in user-defined `Connection` or `Channel` classes has no effect - a `Rails.logger` has to be used instead. Should this solution be accepted, we'd probably need to include a post-install message informing the developer about this state of things.

2. Obviously Action Cable doesn't include a notion of a "controller", however for simplicity I decided to use this name to indicate both `Channel` or `Connection` classes in formatters. So if e.g. a `pong` action defined in `MyChannel < ActionCable::Channel::Base` is called, the Graylog log message would include the following: `MyChannel#pong` and the key of `MyChannel` value in Lograge data hash is still called `controller`.

**Comment by xlts** [comment]
Thx @benlovell. Let me know if anything needs explaining

**Comment by nfedyashev** [comment]
@benlovell is there anything missing?

@xlts thanks for your work btw!

**Comment by xlts** [comment]
Thanks @nfedyashev! @benlovell are there chances of having this reviewed anytime soon?

**Comment by benlovell** [comment]
Thanks for this. Sorry for the delay! I’ll cut a release today or tomorrow. 💖

**Comment by xlts** [comment]
Cool! In the next few days I'll try to work on updates to Readme so that we have this documented & explained properly.

**Comment by benlovell** [comment]
Thanks <3

**Comment by jwhitcraft** [comment]
Because of the MonkeyPatch it breaks [AnyCable](https://github.com/anycable/anycable-rails) see #294

**Comment by palkan** [comment]
> Because of the Monkey-patch it breaks AnyCable see #294

Not only AnyCable is affected, Action Cable's functionality is also changed, compare these two lines, for example:
lograge https://github.com/roidrage/lograge/blob/1729eab7956bb95c5992e4adab251e4f93ff9280/lib/lograge/rails_ext/action_cable/connection/base.rb#L16
rails https://github.com/rails/rails/blob/a11e63f39907f828986f1832329c1b0530ca2aa3/actioncable/lib/action_cable/connection/base.rb#L178

@xlts @benlovell Please, consider replacing this MP with the one not-related on the internal implementation (e.g., using `Module#prepend`) and/or propose the required changes to Rails (I would be glad to help with making it merged).

@jwhitcraft A quick-fix should be smth like:

```ruby
Lograge.class_eval do
  def self.attach_to_action_cable; end
end
```

**Pull request merged**
