### PR TITLE
End support for Ruby 1.9.3 and Rails 3

### PR DESCRIPTION
**Pull request by benlovell**
Ends support for the now unsupported Ruby 1.9.3 and the semi-supported
("severe" security fixes only) Rails 3.2.

This is in readiness for our support of Rails 5, and also to decrease the
support burden for increasingly uncommon configurations.

### CODE REVIEW

**Comment by isqad88** [comment]
But even rails 4 supports 1.9.3 as minimum version :cry:

**Comment by benlovell** [comment]
@isqad88 Internally, this project hasn't changed much over the years and given we're a pretty lightweight dependency, I suspect you could happily use the current released version `0.3.5` if you wanted to support that particular configuration.

**Comment by benlovell** [comment]
@pxlpnk Any thoughts before I merge?

**Comment by pxlpnk** [comment]
We are not trying to rely on 1.9.3 features. The code in general is more focused on rails than on ruby.

I am even pretty sure that lograge runs with all 1.9 rubies. However to slim down our dependencies we should move forward and leave 1.9.3 behind. :wave: :sob:

**Pull request merged**
