### PR TITLE
Resolves outstanding rubocop offenses

### PR DESCRIPTION
**Pull request by benlovell**

### CODE REVIEW

**Comment by benlovell** [comment]
Hmm. This is failing on rubinius across the board.

**Comment by pxlpnk** [comment]
Seems like they changed something in the last release with the serialisation: https://github.com/rubinius/rubinius/compare/v2.5.2...v2.5.3

I have some time tonight to debug this. If we don't want to wait until then we could allow failures on RBX builds. But that would also remove the compatibility.

**Comment by benlovell** [comment]
Something is occurring over in the Oj gem. They claim support for rbx but removed it from their build matrix some time ago. I can't get Oj to build/run with rbx 2.5.3 locally at the moment either so for the time being I'll add rbx to our allowed failures.

**Comment by pxlpnk** [comment]
:+1:

**Comment by pxlpnk** [comment]
@YorickPeterse opened an issue on rbx, adding it here for the reference: https://github.com/rubinius/rubinius/issues/3399

**Pull request merged**
